# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("maillist", "0004_auto_20171002_0804")]

    operations = [
        migrations.AlterModelOptions(
            name="mailinglist",
            options={"base_manager_name": "objects", "ordering": ("verbose_name",)},
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
